import Database from 'better-sqlite3';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// In-memory database for demo
const db = new Database(':memory:');

// Initialize schema
export function initializeDatabase() {
  // Create barcodes table
  db.exec(`
    CREATE TABLE IF NOT EXISTS barcodes (
      barcode_id INTEGER PRIMARY KEY AUTOINCREMENT,
      barcode TEXT NOT NULL UNIQUE,
      generated_by_machine INTEGER NOT NULL DEFAULT 1,
      generated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      status TEXT DEFAULT 'ACTIVE',
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
    )
  `);

  // Create machine_data table
  db.exec(`
    CREATE TABLE IF NOT EXISTS machine_data (
      data_id INTEGER PRIMARY KEY AUTOINCREMENT,
      barcode TEXT NOT NULL,
      machine_id INTEGER NOT NULL,
      processed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
      machine_parameters TEXT NULL,
      notes TEXT NULL,
      status TEXT DEFAULT 'SUCCESS',
      created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
      FOREIGN KEY (barcode) REFERENCES barcodes(barcode),
      UNIQUE(barcode, machine_id)
    )
  `);

  // Create indexes
  db.exec(`
    CREATE INDEX IF NOT EXISTS IDX_machine_data_barcode ON machine_data(barcode);
    CREATE INDEX IF NOT EXISTS IDX_machine_data_machine_id ON machine_data(machine_id);
    CREATE INDEX IF NOT EXISTS IDX_barcodes_status ON barcodes(status);
  `);

  console.log('✅ Database initialized');
}

// Insert demo data
export function insertDemoData() {
  const insertBarcode = db.prepare(`
    INSERT INTO barcodes (barcode, generated_by_machine, generated_at)
    VALUES (?, 1, datetime('now'))
  `);

  const insertMachineData = db.prepare(`
    INSERT INTO machine_data (barcode, machine_id, machine_parameters, notes, processed_at)
    VALUES (?, ?, ?, ?, datetime('now'))
  `);

  // Generate demo barcodes
  const demoBarcodes = [
    'DEMO_BARCODE_001',
    'DEMO_BARCODE_002',
    'DEMO_BARCODE_003',
    'DEMO_BARCODE_004',
    'DEMO_BARCODE_005',
  ];

  demoBarcodes.forEach((barcode, index) => {
    // Insert barcode
    insertBarcode.run(barcode);

    // Machine 1 data (all barcodes)
    insertMachineData.run(
      barcode,
      1,
      JSON.stringify({
        temperature: 25 + index,
        pressure: 101 + index * 0.5,
        voltage: 220 + index,
        graph_data: [1, 2, 3, 4, 5],
      }),
      `Generated by Machine 1 - Sample ${index + 1}`
    );

    // Machine 2 data (first 4 barcodes)
    if (index < 4) {
      insertMachineData.run(
        barcode,
        2,
        JSON.stringify({
          temperature: 27 + index,
          pressure: 103 + index * 0.5,
          humidity: 65 + index,
          scan_quality: index % 2 === 0 ? 'high' : 'medium',
        }),
        `Processed by Machine 2 - Sample ${index + 1}`
      );
    }

    // Machine 3 data (first 2 barcodes)
    if (index < 2) {
      insertMachineData.run(
        barcode,
        3,
        JSON.stringify({
          temperature: 29 + index,
          pressure: 105 + index * 0.5,
          rpm: 1500 + index * 50,
          vibration: 2.3 + index * 0.1,
        }),
        `Processed by Machine 3 - Sample ${index + 1}`
      );
    }

    // Machine 4 data (first barcode only)
    if (index === 0) {
      insertMachineData.run(
        barcode,
        4,
        JSON.stringify({
          temperature: 30.5,
          pressure: 106.8,
          final_weight: 125.6,
          qc_status: 'passed',
        }),
        'Final processing by Machine 4'
      );
    }
  });

  console.log(`✅ Inserted ${demoBarcodes.length} demo barcodes with machine data`);
}

// Barcode operations
export const barcodeOperations = {
  // Generate unique barcode
  generateBarcode(): string {
    const timestamp = Date.now();
    const random = Math.floor(Math.random() * 10000)
      .toString()
      .padStart(4, '0');
    return `BC${timestamp}${random}`;
  },

  // Create new barcode
  createBarcode(barcode: string, machineId: number = 1) {
    const stmt = db.prepare(`
      INSERT INTO barcodes (barcode, generated_by_machine)
      VALUES (?, ?)
    `);
    return stmt.run(barcode, machineId);
  },

  // Get all barcodes
  getAllBarcodes() {
    const stmt = db.prepare(`
      SELECT * FROM barcodes ORDER BY generated_at DESC
    `);
    return stmt.all();
  },

  // Get barcode by ID
  getBarcodeByValue(barcode: string) {
    const stmt = db.prepare(`
      SELECT * FROM barcodes WHERE barcode = ?
    `);
    return stmt.get(barcode);
  },

  // Get barcode processing history
  getBarcodeHistory(barcode: string) {
    const stmt = db.prepare(`
      SELECT 
        md.*,
        json_extract(md.machine_parameters, '$.temperature') as temperature,
        json_extract(md.machine_parameters, '$.pressure') as pressure
      FROM machine_data md
      WHERE md.barcode = ?
      ORDER BY md.machine_id
    `);
    return stmt.all(barcode);
  },

  // Add machine data
  addMachineData(
    barcode: string,
    machineId: number,
    parameters: object,
    notes?: string
  ) {
    const stmt = db.prepare(`
      INSERT INTO machine_data (barcode, machine_id, machine_parameters, notes)
      VALUES (?, ?, ?, ?)
    `);
    return stmt.run(barcode, machineId, JSON.stringify(parameters), notes || '');
  },

  // Check if barcode exists
  barcodeExists(barcode: string): boolean {
    const stmt = db.prepare(`
      SELECT COUNT(*) as count FROM barcodes WHERE barcode = ?
    `);
    const result = stmt.get(barcode) as { count: number };
    return result.count > 0;
  },

  // Check if machine already processed barcode
  machineProcessed(barcode: string, machineId: number): boolean {
    const stmt = db.prepare(`
      SELECT COUNT(*) as count FROM machine_data 
      WHERE barcode = ? AND machine_id = ?
    `);
    const result = stmt.get(barcode, machineId) as { count: number };
    return result.count > 0;
  },

  // Get processing status
  getProcessingStatus() {
    const stmt = db.prepare(`
      SELECT 
        b.barcode,
        b.generated_at,
        COUNT(DISTINCT md.machine_id) as machines_processed,
        GROUP_CONCAT(md.machine_id) as machine_ids,
        MAX(md.machine_id) as last_machine,
        MAX(md.processed_at) as last_processed_at
      FROM barcodes b
      LEFT JOIN machine_data md ON b.barcode = md.barcode
      GROUP BY b.barcode, b.generated_at
      ORDER BY b.generated_at DESC
    `);
    return stmt.all();
  },
};

export default db;
