import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
import { initializeSQLServerDatabase, sqlServerOperations } from './database-sqlserver.js';

dotenv.config();

const app = express();
const PORT = process.env.PORT || 3003;

app.use(cors());
app.use(express.json());

// Initialize SQL Server database on startup
initializeSQLServerDatabase().catch((error) => {
  console.error('Failed to initialize database:', error);
  process.exit(1);
});

app.get('/health', (req, res) => {
  res.json({ service: 'scanning', status: 'ok', database: 'SQL Server' });
});

// ─── Generate new barcode ────────────────────────────────────────────────────
app.post('/api/barcode/generate', async (req, res) => {
  try {
    const { machineId = 1, userId } = req.body;
    const barcode = sqlServerOperations.generateBarcode();

    await sqlServerOperations.createBarcode(barcode, machineId);
    await sqlServerOperations.addMachineData(
      barcode,
      machineId,
      { temperature: 25.0, pressure: 101.3, voltage: 220, generated: true },
      `Generated by Machine ${machineId}`
    );

    await sqlServerOperations.logActivity('GENERATE', 'SUCCESS', {
      barcode, machineId, userId, ip: req.ip,
      details: { action: 'Barcode generated' },
    });

    res.json({ success: true, barcode, message: 'Barcode generated successfully' });
  } catch (error) {
    const { machineId, userId } = req.body || {};
    await sqlServerOperations.logActivity('GENERATE', 'FAILED', {
      machineId, userId, ip: req.ip,
      error: error instanceof Error ? error.message : 'Unknown error',
    });
    console.error('Error generating barcode:', error);
    res.status(500).json({ success: false, error: 'Failed to generate barcode' });
  }
});

// ─── Get all barcodes ────────────────────────────────────────────────────────
app.get('/api/barcodes', async (req, res) => {
  try {
    const barcodes = await sqlServerOperations.getAllBarcodes();
    res.json({ success: true, barcodes });
  } catch (error) {
    console.error('Error fetching barcodes:', error);
    res.status(500).json({ success: false, error: 'Failed to fetch barcodes' });
  }
});

// ─── Get barcode details with history ────────────────────────────────────────
app.get('/api/barcode/:barcode', async (req, res) => {
  try {
    const { barcode } = req.params;
    const barcodeData = await sqlServerOperations.getBarcodeByValue(barcode);

    if (!barcodeData) {
      return res.status(404).json({ success: false, error: 'Barcode not found' });
    }

    const history = await sqlServerOperations.getBarcodeHistory(barcode);
    res.json({ success: true, barcode: barcodeData, history });
  } catch (error) {
    console.error('Error fetching barcode:', error);
    res.status(500).json({ success: false, error: 'Failed to fetch barcode details' });
  }
});

// ─── Scan/process a barcode ──────────────────────────────────────────────────
app.post('/api/scan', async (req, res) => {
  try {
    const { barcode, machineId, parameters, notes, userId } = req.body;

    if (!barcode || !machineId) {
      await sqlServerOperations.logActivity('SCAN', 'FAILED', {
        barcode, machineId, userId, ip: req.ip,
        error: 'Missing barcode or machineId',
      });
      return res.status(400).json({ success: false, error: 'Barcode and machineId are required' });
    }

    if (!(await sqlServerOperations.barcodeExists(barcode))) {
      await sqlServerOperations.logActivity('SCAN', 'FAILED', {
        barcode, machineId, userId, ip: req.ip,
        error: 'Barcode not found',
      });
      return res.status(404).json({ success: false, error: 'Barcode not found. Please generate it first.' });
    }

    if (await sqlServerOperations.machineProcessed(barcode, machineId)) {
      await sqlServerOperations.logActivity('SCAN', 'FAILED', {
        barcode, machineId, userId, ip: req.ip,
        error: `Machine ${machineId} already processed this barcode`,
        details: { reason: 'DUPLICATE_SCAN' },
      });
      return res.status(409).json({ success: false, error: `Machine ${machineId} has already processed this barcode` });
    }

    // Validate sequential processing
    const sequentialCheck = await sqlServerOperations.validateSequentialProcessing(barcode, machineId);
    if (!sequentialCheck.valid) {
      await sqlServerOperations.logActivity('SCAN', 'FAILED', {
        barcode, machineId, userId, ip: req.ip,
        error: sequentialCheck.message,
        details: { reason: 'SEQUENCE_VIOLATION' },
      });
      return res.status(400).json({ success: false, error: sequentialCheck.message });
    }

    await sqlServerOperations.addMachineData(barcode, machineId, parameters || {}, notes || `Processed by Machine ${machineId}`);
    const history = await sqlServerOperations.getBarcodeHistory(barcode);

    await sqlServerOperations.logActivity('SCAN', 'SUCCESS', {
      barcode, machineId, userId, ip: req.ip,
      details: { machinesProcessed: history.length },
    });

    res.json({ success: true, message: `Barcode processed by Machine ${machineId}`, history });
  } catch (error) {
    const { barcode, machineId, userId } = req.body || {};
    await sqlServerOperations.logActivity('SCAN', 'FAILED', {
      barcode, machineId, userId, ip: req.ip,
      error: error instanceof Error ? error.message : 'Unknown error',
    });
    console.error('Error processing barcode:', error);
    res.status(500).json({ success: false, error: 'Failed to process barcode' });
  }
});

// ─── Enhanced Dashboard ──────────────────────────────────────────────────────
app.get('/api/status', async (req, res) => {
  try {
    const status = await sqlServerOperations.getDashboardStats();
    res.json({ success: true, status });
  } catch (error) {
    console.error('Error fetching status:', error);
    res.status(500).json({ success: false, error: 'Failed to fetch status' });
  }
});

app.get('/api/dashboard', async (req, res) => {
  try {
    const status = await sqlServerOperations.getDashboardStats();
    res.json({ success: true, status });
  } catch (error) {
    console.error('Error fetching dashboard:', error);
    res.status(500).json({ success: false, error: 'Failed to fetch dashboard' });
  }
});

// ─── Reports ─────────────────────────────────────────────────────────────────

/** Summary report with date range */
app.get('/api/reports/summary', async (req, res) => {
  try {
    const { period = 'all', startDate, endDate } = req.query as { period?: string; startDate?: string; endDate?: string };
    const summary = await sqlServerOperations.getReportSummary(period, startDate, endDate);
    res.json({ success: true, summary });
  } catch (error) {
    console.error('Error fetching report summary:', error);
    res.status(500).json({ success: false, error: 'Failed to fetch report summary' });
  }
});

/** Machine activity breakdown */
app.get('/api/reports/machine-activity', async (req, res) => {
  try {
    const { period = 'all', startDate, endDate } = req.query as { period?: string; startDate?: string; endDate?: string };
    const machines = await sqlServerOperations.getMachineActivity(period, startDate, endDate);
    res.json({ success: true, machines });
  } catch (error) {
    console.error('Error fetching machine activity:', error);
    res.status(500).json({ success: false, error: 'Failed to fetch machine activity' });
  }
});

/** Completion stats */
app.get('/api/reports/completion', async (req, res) => {
  try {
    const { period = 'all', startDate, endDate } = req.query as { period?: string; startDate?: string; endDate?: string };
    const items = await sqlServerOperations.getCompletionStats(period, startDate, endDate);
    res.json({ success: true, items });
  } catch (error) {
    console.error('Error fetching completion stats:', error);
    res.status(500).json({ success: false, error: 'Failed to fetch completion stats' });
  }
});

/** Failed scans */
app.get('/api/reports/failed-scans', async (req, res) => {
  try {
    const { period = 'all', startDate, endDate } = req.query as { period?: string; startDate?: string; endDate?: string };
    const failures = await sqlServerOperations.getFailedScans(period, startDate, endDate);
    res.json({ success: true, failures });
  } catch (error) {
    console.error('Error fetching failed scans:', error);
    res.status(500).json({ success: false, error: 'Failed to fetch failed scans' });
  }
});

/** Hourly activity chart data */
app.get('/api/reports/hourly', async (req, res) => {
  try {
    const { period = 'today', startDate, endDate } = req.query as { period?: string; startDate?: string; endDate?: string };
    const hourly = await sqlServerOperations.getHourlyActivity(period, startDate, endDate);
    res.json({ success: true, hourly });
  } catch (error) {
    console.error('Error fetching hourly activity:', error);
    res.status(500).json({ success: false, error: 'Failed to fetch hourly activity' });
  }
});

/** Daily activity trend data */
app.get('/api/reports/daily', async (req, res) => {
  try {
    const { period = 'month', startDate, endDate } = req.query as { period?: string; startDate?: string; endDate?: string };
    const daily = await sqlServerOperations.getDailyActivity(period, startDate, endDate);
    res.json({ success: true, daily });
  } catch (error) {
    console.error('Error fetching daily activity:', error);
    res.status(500).json({ success: false, error: 'Failed to fetch daily activity' });
  }
});

/** Full barcode journey */
app.get('/api/reports/barcode-journey/:barcode', async (req, res) => {
  try {
    const { barcode } = req.params;
    const journey = await sqlServerOperations.getBarcodeJourney(barcode);
    if (!journey) {
      return res.status(404).json({ success: false, error: 'Barcode not found' });
    }
    res.json({ success: true, journey });
  } catch (error) {
    console.error('Error fetching barcode journey:', error);
    res.status(500).json({ success: false, error: 'Failed to fetch barcode journey' });
  }
});

/** Activity log with filtering & pagination */
app.get('/api/reports/activity-log', async (req, res) => {
  try {
    const { page = '1', limit = '50', action, status, machineId, period, startDate, endDate } = req.query as Record<string, string>;
    const result = await sqlServerOperations.getActivityLog(
      parseInt(page),
      parseInt(limit),
      {
        action: action || undefined,
        status: status || undefined,
        machineId: machineId ? parseInt(machineId) : undefined,
        period: period || undefined,
        startDate: startDate || undefined,
        endDate: endDate || undefined,
      },
    );
    res.json({ success: true, ...result });
  } catch (error) {
    console.error('Error fetching activity log:', error);
    res.status(500).json({ success: false, error: 'Failed to fetch activity log' });
  }
});

// Clear all data (for testing)
app.post('/api/clear-database', async (req, res) => {
  try {
    await sqlServerOperations.dropDatabase();
    res.json({ success: true, message: 'Database dropped and recreated with fresh empty tables' });
  } catch (error) {
    console.error('Error clearing database:', error);
    res.status(500).json({ success: false, error: 'Failed to clear database' });
  }
});

// Reset database — clears data but keeps machines
app.post('/api/reset-database', async (req, res) => {
  try {
    await sqlServerOperations.resetDatabase();
    res.json({ success: true, message: 'All barcode data cleared. Machines preserved.' });
  } catch (error) {
    console.error('Error resetting database:', error);
    res.status(500).json({ success: false, error: 'Failed to reset database' });
  }
});

// Machine Management Endpoints (NEW)
app.get('/api/machines', async (req, res) => {
  try {
    const machines = await sqlServerOperations.getAllMachines();
    res.json({ success: true, machines });
  } catch (error) {
    console.error('Error fetching machines:', error);
    res.status(500).json({ success: false, error: 'Failed to fetch machines' });
  }
});

app.get('/api/machines/:id', async (req, res) => {
  try {
    const machineId = parseInt(req.params.id);
    const machine = await sqlServerOperations.getMachineById(machineId);
    if (!machine) {
      return res.status(404).json({ success: false, error: 'Machine not found' });
    }
    res.json({ success: true, machine });
  } catch (error) {
    console.error('Error fetching machine:', error);
    res.status(500).json({ success: false, error: 'Failed to fetch machine' });
  }
});

app.post('/api/machines', async (req, res) => {
  try {
    const { machineId, machineName, machineCode, sequenceOrder, description, canGenerateBarcode } = req.body;
    
    if (!machineId || !machineName || !machineCode || sequenceOrder === undefined) {
      return res.status(400).json({ success: false, error: 'machineId, machineName, machineCode, and sequenceOrder are required' });
    }

    await sqlServerOperations.createMachine(machineId, machineName, machineCode, sequenceOrder, description, canGenerateBarcode);
    res.json({ success: true, message: 'Machine created successfully' });
  } catch (error) {
    console.error('Error creating machine:', error);
    res.status(500).json({ success: false, error: 'Failed to create machine. May be duplicate ID or sequence.' });
  }
});

app.put('/api/machines/:id', async (req, res) => {
  try {
    const machineId = parseInt(req.params.id);
    const updates = req.body;
    
    await sqlServerOperations.updateMachine(machineId, updates);
    res.json({ success: true, message: 'Machine updated successfully' });
  } catch (error) {
    console.error('Error updating machine:', error);
    res.status(500).json({ success: false, error: 'Failed to update machine' });
  }
});

app.delete('/api/machines/:id', async (req, res) => {
  try {
    const machineId = parseInt(req.params.id);
    await sqlServerOperations.deleteMachine(machineId);
    res.json({ success: true, message: 'Machine deactivated successfully' });
  } catch (error) {
    console.error('Error deleting machine:', error);
    res.status(500).json({ success: false, error: 'Failed to delete machine' });
  }
});

app.listen(PORT, () => {
  console.log(`🔍 Scanning Service running on port ${PORT}`);
  console.log(`📊 Connected to SQL Server at ${process.env.DB_HOST}:${process.env.DB_PORT}`);
});
