packages:
  - apps/**
  - features/**
  - templates/**
  - tools/**
  - '!**/.*/**'

catalog:
  '@expo/vector-icons': ^14.0.5
  '@hey-api/openapi-ts': ^0.92.3
  '@react-native-async-storage/async-storage': 2.1.0
  '@react-navigation/native': ^7.0.12
  '@react-navigation/native-stack': ^7.1.11
  '@reduxjs/toolkit': ^2.5.1
  '@tanstack/react-query': ^5.64.2
  '@testing-library/jest-dom': ^6.9.1
  '@testing-library/react': ^16.3.0
  '@testing-library/react-native': ^12.9.0
  '@testing-library/user-event': ^14.6.1
  '@trivago/prettier-plugin-sort-imports': 5.2.2
  '@types/bcryptjs': ^2.4.6
  '@types/cors': ^2.8.17
  '@types/express': ^5.0.0
  '@types/jsonwebtoken': ^9.0.7
  '@types/mssql': ^9.1.5
  '@types/node': ^22.10.7
  '@types/pg': ^8.11.6
  '@types/react': ~19.1.10
  '@types/react-dom': ~19.0.6
  '@untitledui/icons': ^0.0.19
  '@vitejs/plugin-react': ^5.1.1
  '@vitest/coverage-v8': 4.0.15
  '@zxing/library': ^0.21.3
  axios: ^1.12.2
  bcryptjs: ^2.4.3
  clsx: ^2.1.1
  cors: ^2.8.5
  dotenv: ^16.4.7
  eslint: ^9.39.1
  expo: ~54.0.0
  expo-constants: ~18.0.0
  expo-dev-client: ~6.0.0
  expo-font: ~14.0.0
  expo-linking: ~8.0.0
  expo-localization: ~17.0.8
  expo-router: ~6.0.23
  expo-splash-screen: ~1.0.0
  expo-status-bar: ~3.0.9
  expo-system-ui: ~4.1.0
  expo-web-browser: ~15.0.0
  express: ^4.21.2
  globals: ^16.0.0
  i18next: ^25.8.11
  jsonwebtoken: ^9.0.2
  lucide-react-native: ^0.475.0
  mssql: ^11.0.1
  nativewind: 4.2.1
  pg: ^8.12.0
  prettier: 3.6.2
  react: 19.1.0
  react-dom: 19.1.0
  react-error-boundary: ^6.0.0
  react-i18next: ^16.5.4
  react-native: 0.81.5
  react-native-gesture-handler: ~2.28.0
  react-native-reanimated: ~4.1.1
  react-native-safe-area-context: 5.6.2
  react-native-screens: ~4.16.0
  react-native-svg: 15.12.1
  react-native-web: ^0.21.0
  react-router: ^7.6.2
  tailwindcss: 3.4.19
  tsx: 4.21.0
  typescript: ~5.9.2
  vite: ^6.0.7
  vitest: 4.0.15
  zustand: ^5.0.2
